---
title: "Wild Data"
author: "Felicia Cruz"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

## Read in the data
```{r}
mack_verts <- read_csv(here::here("data/AS00601.csv"))
```

## A bit of data wrangling 

```{r}
mack_verts <- mack_verts %>% clean_names()
```

```{r}
mc_wt_5 <- mack_verts$weight[5]

mc_length_8_20 <- mack_verts$length1[8:20]

mc_dates <- as.vector(mack_verts$sampledate)
#mc_dates
```

## Salamander subset
```{r}
mc_salamanders <- mack_verts %>% filter(species == "DITE")
```

## Scatterplot
```{r}
salamander_scatter <- ggplot(data = mack_verts, aes(x = length1, y = weight)) +
  geom_point(aes(color = species),
             alpha = 0.5,
             size = 0.75) +
  labs(title = "Salamander Snout-vent Length vs. Weight",
       subtitle = "Aquatice Vertebrate Population Study in Mack Creek",
       caption = "source: Environmental Data Initiative",
       x = "snout-vent length (mm)",
       y = "weight (g)",
       color = "Species") +
  theme_minimal()

ggsave(here("figs", "salamander_size.png"), plot = salamander_scatter)
```

# cutthroat plot 

```{r}
mc_trout <- mack_verts %>% filter(species == "ONCL") 

mc_trout_scatter_reach <- ggplot(data = mc_trout, aes(x = length1, y = weight)) + 
  geom_point(aes(color = reach),
             alpha = 0.5) + 
  scale_color_manual(values = c("yellow4", "magenta4", "cyan4")) + 
  facet_wrap(~reach) +
  labs(title = "Cutthroat trout measurements by reach",
       x = "length (mm)",
       y = "weight", 
       color = "Reach")

ggsave(here("figs", "cutthroat_size.png"), plot = mc_trout_scatter_reach)
```

